spring:
  application:
    name: collector
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: kafka.serializer.GeneralAvroSerializer
      client-id: telemetry.collector

logging:
  level:
    ru.practicum.telemetry: TRACE
    org:
      springframework: ERROR
      apache.kafka: WARN

collector:
  kafka:
    topics:
      sensors-events: telemetry.sensors.v1
      hubs-events: telemetry.hubs.v1
